import { Injectable, Output } from '@angular/core';
import { Boardgame } from '../models/boardgame';
import { Subject } from 'rxjs/Subject';

@Injectable()
export class BoardgamesService {

  mockBoardGames = new Subject<Boardgame[]>();

  constructor() {  }

  getBoardGames() {
    this.mockBoardGames.next([
      {
        'title': 'Dominion',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/7mkW_JrUx0PSa4Ame3zzsLE0BVY=/fit-in/246x300/pic394356.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 200,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 200,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 200,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 200,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 200,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 200,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 200,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 3.56,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 3.56,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 3.56,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 3.56,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 3.56,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 3.56,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 3.56,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 3.56,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 5,
        'max_player_count': 5,
        'min_time': 80,
        'max_time': 100,
        'complexity': 3.56,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      },
      {
        'title': 'Munchkin',
        'game_id': 1,
        'min_player_count': 2,
        'max_player_count': 4,
        'min_time': 30,
        'max_time': 60,
        'complexity': 2.37,
        'thumbnail': 'https://cf.geekdo-images.com/itemrep/img/kPfLihonl0sXH47uh6fvXlJCQvQ=/fit-in/246x300/pic1871016.jpg',
      }
    ]);
  }

}
